## Comparison Operators

comparison operator between any two numbers or variable creates boolean objects which can later be used subsetting arrays, lists or DataFrames

#### Numeric Comparison

In [1]:
2 < 3

True

In [2]:
2 == 3

False

In [3]:
2 <= 3

True

we can also use comparison operators on variables as shown below

In [4]:
x = 2

In [5]:
y = 3

In [6]:
x < y

True

These operations can also be used for strings

In [7]:
'hari' > 'ram'

False

## Boolean Operators

+ and
+ or
+ not

they help to combine different boolean values together, for example

#### and operator

it returns True if and only if both the conditions are True

In [8]:
x = 12

In [9]:
x > 5

True

In [10]:
x < 15

True

In [11]:
# we can combine above two comparison operations using the boolean operator 'and'
x > 5 and x < 15

True

#### or operator

it returns True if any one of the conditions returns True

In [12]:
x > 5 or x < 10

True

#### not operator

it simply negates the boolean value we are using, for example

In [13]:
not True

False

In [14]:
not False

True

## Boolean Operators with NumPy arrays

In [15]:
import numpy as np

In [16]:
bmi = np.array([21, 22, 23, 24, 25])

In [17]:
bmi > 22 and bmi < 24

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

why is the above error?

In [18]:
bmi > 22

array([False, False,  True,  True,  True])

In [19]:
bmi < 24

array([ True,  True,  True, False, False])

For NumPy arrays we have different sets of boolean operators
+ logical_and
+ logical_or
+ logical_not

In [20]:
np.logical_and(bmi > 22, bmi < 24)

array([False, False,  True, False, False])

In [21]:
bmi[np.logical_and(bmi > 22, bmi < 24)]

array([23])

## Conditional Statements

conditional statements are used to alter the flow of scripts
+ if statements
+ elif statements
+ else statements

In [22]:
z = 5

In [23]:
if z % 2 == 0:
    print('z is even')
    print(2 + 2)
    print(2 + 3)
print(2 + 5)

7


In [24]:
"ram" = "rajiv"

SyntaxError: can't assign to literal (<ipython-input-24-bfdd006dabeb>, line 1)

In [25]:
if z % 2 == 0:
    print('z is even')
else:
    print('z is odd')

z is odd


Suppose, you are working as a data analyst for a real estate firm. And you need to convert a coninuous variable (floor area of a house) into a categorical variable with three levels (low floor area, medium floor area and high floor area). How would you do that using conditional statements.

In [26]:
floor_area = 1000

In [27]:
if floor_area < 900:
    print('low floor area')
elif floor_area < 1500:
    print('medium floor area')
else:
    print('high floor area')

medium floor area


## Filtering Pandas DataFrame

In [28]:
import pandas as pd

In [29]:
brics = pd.read_csv('brics.csv', index_col=0)

In [30]:
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

Select countries with area over 8 million sq km

+ select the area column
+ do comparison on area column
+ use the result to select the countries

In [31]:
brics['area']

BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [32]:
brics['area'] > 8

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [33]:
large_area = brics['area'] > 8
large_area

BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [34]:
brics[large_area]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

writing all the above three pieces of code in one line below

In [38]:
brics[brics['area'] > 8]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

#### applying boolean operators in a DataFrame for multiple conditions

In [39]:
brics[np.logical_and(brics['area'] > 8, brics['area'] < 10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0